# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ya Zhuang
email: zhuangya@gmail.com
description: >
  Just another developer
logo: "/assets/images/logo.jpg"
baseurl: "/_" # the subpath of your site, e.g. /blog
url: "http://zhuangya.me" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Ya Zhuang'
bio: >
  Doodu
author_image: "/assets/images/author.jpg"
twitter_username: yazhuang
github_username:  zhuangya

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
